const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={busy:false,currentLessonId:null,history:[],content:[],catalog:[],documents:[],hierarchy:{nodes:[],documents:[]},expandedNodes:new Set(),config:{},topicChoices:[],topicActiveIndex:-1};
const normalizeName=value=>String(value||'').trim().replace(/\s+/g,' ').toLocaleLowerCase();
const escapeHtml=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const statusMessages={CONNECTION_FAILED:'The application service is unavailable. Start the Dell service and try again.',GATEWAY_NOT_CONFIGURED:'The secure Dell connection has not been configured yet.',DELL_API_UNAVAILABLE:'The Dell service is offline or its secure tunnel is disconnected.',MODEL_OFFLINE:'The model service is unavailable. Review Setup & health and try again.',BUSY:'Another generation request is still running. Wait for it to finish and try again.',UPLOAD_BUSY:'Another document is still processing. Wait for it to finish and try again.',INTERNAL_ERROR:'The application could not complete this request. Please try again.',DELETE_FAILED:'The selected library item could not be deleted.',LESSON_WITHHELD:'The generated lesson was withheld because it did not pass the factual review.',WRONG_PORTAL:'This older Pages address cannot reach the Dell API. Open https://learn-with-stories.aaankurankur.workers.dev and retry.'};
function safeUiText(value,fallback='The request could not be completed.',maxLength=320){const text=String(value||'').replace(/[\u0000-\u001f\u007f]+/g,' ').replace(/\s+/g,' ').trim();const technical=/(?:traceback|stack trace|syntaxerror|typeerror|referenceerror|sqlite|urllib|<!doctype|<html|<script|```|\bfunction\s*\(|\bselect\s+.+\bfrom\b|\binsert\s+into\b|\bupdate\s+.+\bset\b|(?:[a-z]:\\|\/(?:app|usr|home|var)\/)|\bat\s+[\w$.]+\s*\()/i;return !text||text.length>maxLength||technical.test(text)?fallback:text}
function publicErrorMessage(error,fallback='The request could not be completed.'){const status=String(error?.status||'').toUpperCase();if(statusMessages[status])return statusMessages[status];return safeUiText(error?.message,fallback)}
const levelGuides={10:["Very simple","Concrete words, one idea at a time, with frequent recap."],15:["High school clear","Straightforward language, simple cause and effect, and every exam term explained."],18:["Adult learner","Adult vocabulary, realistic examples, linked causes, and standard exam terminology."],28:["Detailed adult","Precise language, nuanced analogy, compact pace, and important qualifications."]};
function nearestLevel(v){return Object.keys(levelGuides).map(Number).sort((a,b)=>Math.abs(a-v)-Math.abs(b-v))[0]}
async function api(path,options={}){const headers=options.body instanceof File?options.headers||{}:{"Content-Type":"application/json",...(options.headers||{})};let response;try{response=await fetch(path,{...options,headers})}catch{throw{status:'CONNECTION_FAILED',message:statusMessages.CONNECTION_FAILED}}let body;try{body=await response.json()}catch{const status=location.hostname==='learnwithstories.pages.dev'?'WRONG_PORTAL':'INVALID_RESPONSE';throw{status,message:statusMessages[status]||'The application service returned an unreadable response. Restart the Dell service and try again.'}}if(!response.ok){const status=/^[A-Z][A-Z0-9_]{1,40}$/.test(String(body?.status||''))?String(body.status):'REQUEST_FAILED';throw{status,message:publicErrorMessage({status,message:body?.message},`The request failed (HTTP ${response.status}). Please try again.`)}}return body}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name&&b.classList.contains('nav-item')));$('.sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'});if(name==='progress')loadProgress();if(name==='library')loadLibrary();if(name==='exam')window.dispatchEvent(new CustomEvent('exam:view'));if(name==='settings'){loadSettings();loadMemories()}}
$$('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();switchView(b.dataset.view)}));$('#menuButton').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
$('#todayDate').textContent=new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short'}).format(new Date());
$('#level').addEventListener('input',e=>{const v=Number(e.target.value),g=levelGuides[nearestLevel(v)];$('#levelOutput').textContent=v;$('#levelName').textContent=g[0];$('#levelDescription').textContent=g[1]});
function selectedCatalog(){return state.catalog.find(item=>item.subject===$('#subject').value)}
function closeTopicSuggestions(){state.topicActiveIndex=-1;$('#topicSuggestions').classList.add('hidden');$('#concept').setAttribute('aria-expanded','false')}
function renderTopicSuggestions(open=true){const menu=$('#topicSuggestions'),query=normalizeName($('#concept').value),matches=state.topicChoices.filter(topic=>!query||normalizeName(topic).includes(query)).slice(0,40);state.topicActiveIndex=-1;menu.innerHTML=matches.length?matches.map((topic,index)=>`<button type="button" role="option" data-topic-index="${index}" data-topic-value="${escapeHtml(topic)}">${escapeHtml(topic)}</button>`).join(''):'<span class="topic-empty">No matching saved topic. You can keep your manually entered name.</span>';menu.classList.toggle('hidden',!open);$('#concept').setAttribute('aria-expanded',String(open))}
function chooseTopic(value){$('#concept').value=value;closeTopicSuggestions();$('#concept').dispatchEvent(new Event('input',{bubbles:true}));$('#concept').focus()}
function refreshTopicChoices(){const selected=selectedCatalog(),input=$('#concept');input.value='';input.disabled=false;input.placeholder=selected?'Choose or type an optional topic':'Select a subject first';state.topicChoices=selected?[...new Map(selected.topics.map(x=>[normalizeName(x),x])).values()]:[];closeTopicSuggestions();$('#coverageHint').textContent=selected?`${state.topicChoices.length} topic suggestions. Leave blank to search all ${selected.subject} material.`:'Choose a subject to load optional topic suggestions.';$('#lessonFormError').classList.add('hidden')}
async function loadCatalog(){try{state.catalog=await api('/api/catalog');const select=$('#subject'),previous=select.value;select.innerHTML='<option value="">Select a subject</option>'+state.catalog.map(item=>`<option value="${escapeHtml(item.subject)}">${escapeHtml(item.subject)} (${item.topics.length} topics)</option>`).join('');if(state.catalog.some(item=>item.subject===previous))select.value=previous;refreshTopicChoices()}catch{$('#subject').innerHTML='<option value="">Subjects unavailable</option>';$('#coverageHint').textContent='The local content catalog could not be loaded.'}}
$('#subject').addEventListener('change',refreshTopicChoices);
$('#concept').addEventListener('input',()=>{const selected=selectedCatalog(),value=normalizeName($('#concept').value);if(!selected){$('#coverageHint').textContent='Choose a subject before using a topic filter.';closeTopicSuggestions();return}const matches=state.topicChoices.filter(topic=>normalizeName(topic).includes(value)),exact=state.topicChoices.find(topic=>normalizeName(topic)===value);$('#coverageHint').textContent=exact?`Evidence will be restricted to “${exact}”.`:value?`${matches.length} matching suggestion${matches.length===1?'':'s'}. Choose one to restrict evidence, or keep your manual name.`:`Searching all approved ${selected.subject} material.`;renderTopicSuggestions(true)});
$('#concept').addEventListener('focus',()=>{if(selectedCatalog())renderTopicSuggestions(true)});
$('#topicToggle').addEventListener('click',()=>{$('#topicSuggestions').classList.contains('hidden')?renderTopicSuggestions(true):closeTopicSuggestions()});
$('#topicSuggestions').addEventListener('mousedown',event=>event.preventDefault());
$('#topicSuggestions').addEventListener('click',event=>{const option=event.target.closest('[data-topic-value]');if(option)chooseTopic(option.dataset.topicValue)});
$('#concept').addEventListener('keydown',event=>{const menu=$('#topicSuggestions'),options=[...menu.querySelectorAll('[data-topic-value]')];if(event.key==='Escape'){closeTopicSuggestions();return}if(!['ArrowDown','ArrowUp','Enter'].includes(event.key))return;if(menu.classList.contains('hidden'))renderTopicSuggestions(true);const current=[...menu.querySelectorAll('[data-topic-value]')];if(!current.length)return;if(event.key==='Enter'&&state.topicActiveIndex>=0){event.preventDefault();chooseTopic(current[state.topicActiveIndex].dataset.topicValue);return}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();state.topicActiveIndex=(state.topicActiveIndex+(event.key==='ArrowDown'?1:-1)+current.length)%current.length;current.forEach((item,index)=>item.classList.toggle('active',index===state.topicActiveIndex));current[state.topicActiveIndex].scrollIntoView({block:'nearest'})}});
document.addEventListener('click',event=>{if(!event.target.closest('.topic-combobox'))closeTopicSuggestions()});
function setModelState(online,text){const hosted=state.config.model_provider==='openai',provider=hosted?'OpenAI':'local model PC';$('#modelPill').classList.toggle('online',online);$('#modelPill').classList.toggle('offline',!online);$('#modelPillText').textContent=text;$('#modelNotice').classList.toggle('hidden',online);$('#healthTitle').textContent=online?`${provider} is online`:`${provider} is unavailable`;$('#healthDetail').textContent=online?`${state.config.model_name} is reachable through ${hosted?'the OpenAI API':'the private LAN'}.`:hosted?'New lessons are unavailable. Run configure-openai-key.cmd, confirm API billing/access, and restart the app.':'New lessons are unavailable. Check the RTX PC, Ollama, firewall, IP, and configured model.';$('.health-card').classList.toggle('online',online);$('.health-card').classList.toggle('offline',!online)}
async function checkHealth(){setModelState(false,'Checking model…');try{const h=await api('/api/health');setModelState(true,`${h.configured_model} online`);return true}catch{setModelState(false,'Model PC offline');return false}}
$('#healthButton').addEventListener('click',checkHealth);$('#mobileHealth').addEventListener('click',()=>switchView('settings'));
async function loadConfig(){try{state.config=await api('/api/config');$('#language').value=state.config.default_language;$('#level').value=state.config.default_level;$('#level').dispatchEvent(new Event('input'));renderConfig()}catch{}}
function renderConfig(){$('#configList').innerHTML=`<dt>Provider</dt><dd>${escapeHtml(state.config.model_provider||'ollama')}</dd><dt>Model</dt><dd>${escapeHtml(state.config.model_name||'Not configured')}</dd><dt>API keys</dt><dd>${state.config.model_provider==='openai'?`${Number(state.config.configured_api_keys||0)} securely configured`:'Not required for Ollama'}</dd><dt>Default language</dt><dd>${escapeHtml(state.config.default_language||'English')}</dd><dt>Default level</dt><dd>${escapeHtml(state.config.default_level||18)}</dd><dt>Application</dt><dd>Dell / ${escapeHtml(location.host)}</dd>`}
function historyMarkup(items,full=false){if(!items.length)return '<div class="empty-mini">No lessons have been prepared yet.</div>';return items.map(item=>full?`<button class="history-line" data-lesson-id="${item.id}"><strong>${escapeHtml(item.question||item.concept)}</strong><span>${escapeHtml(item.subject)}</span><span>Level ${item.understanding_level}</span><span>${escapeHtml(item.created_at)}</span></button>`:`<div class="history-item" data-lesson-id="${item.id}"><div><strong>${escapeHtml(item.question||item.concept)}</strong><small>${escapeHtml(item.subject)}${item.concept?` • ${escapeHtml(item.concept)}`:''} • Level ${item.understanding_level}</small></div><span class="status-tag">${escapeHtml(item.status)}</span></div>`).join('')}
async function loadHistory(){try{state.history=await api('/api/history');$('#historyList').innerHTML=historyMarkup(state.history);bindHistory($('#historyList'))}catch{$('#historyList').innerHTML='<div class="empty-mini">History unavailable.</div>'}}
function bindHistory(root){root.querySelectorAll('[data-lesson-id]').forEach(el=>el.addEventListener('click',()=>openSavedLesson(Number(el.dataset.lessonId))))}
async function openSavedLesson(id){try{const r=await api(`/api/lessons/${id}`);switchView('learn');renderLesson({...r,cached:true},{subject:r.subject,concept:r.concept,question:r.question,level:r.level,minutes:'saved'})}catch(e){showError(e)}}
function setBusy(b){state.busy=b;$('#createButton').disabled=b;$('#resultPanel').classList.remove('hidden');$('#loadingState').classList.toggle('hidden',!b);if(b){$('#errorState').classList.add('hidden');$('#lessonState').classList.add('hidden');let messages=['Retrieving approved facts…','Planning a memorable teaching story…','Writing at your understanding level…','Checking every exam-relevant claim…'];let i=0;$('#loadingTitle').textContent=messages[0];state.loadingTimer=setInterval(()=>{$('#loadingTitle').textContent=messages[++i%messages.length]},2300)}else{clearInterval(state.loadingTimer)}}
function showError(e){setBusy(false);const title=e.status==='NEEDS_EVIDENCE'?'Approved evidence is needed':e.status==='MODEL_OFFLINE'?'The model service is unavailable':e.status==='BUSY'?'One lesson at a time':e.status==='CONNECTION_FAILED'||e.status==='DELL_API_UNAVAILABLE'?'The learning service is offline':'The lesson was safely withheld';const message=publicErrorMessage(e,'The tutor withheld this lesson rather than show an uncertain result.');$('#errorState').innerHTML=`<h2>${escapeHtml(title)}</h2><p>${escapeHtml(message)}</p><small>Technical details are recorded only on the Dell service.</small>`;$('#errorState').classList.remove('hidden');$('#resultPanel').scrollIntoView({behavior:'smooth'})}
function normalizeQuestions(qs){return(qs||[]).map(q=>typeof q==='string'?{question:q,options:[],correct_index:-1,explanation:'Answer review is unavailable for this older cached lesson.'}:q)}
function renderQuestions(items){$('#questions').innerHTML=items.map((q,i)=>`<fieldset class="question-card" data-correct="${q.correct_index}"><p>${i+1}. ${escapeHtml(q.question)}</p><div class="option-grid">${(q.options||[]).map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"><span>${escapeHtml(o)}</span></label>`).join('')}</div><p class="explanation">${escapeHtml(q.explanation||'')}</p></fieldset>`).join('');$('#quizForm').classList.toggle('hidden',items.some(q=>!q.options.length))}
function renderLesson(result,req){setBusy(false);state.currentLessonId=result.lesson_id;const l=result.lesson;$('#lessonTitle').textContent=l.title||req.concept;$('#lessonMeta').textContent=`${req.subject} • Understanding level ${req.level} • ${req.minutes} minute lesson`;$('#cacheBadge').textContent=result.cached?'VERIFIED CACHE':result.repaired?'REPAIRED & RE-VERIFIED':'NEWLY VERIFIED';$('#storyCopy').textContent=l.story||'';$('#examTruth').innerHTML=(l.exam_truth||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('');$('#memoryHook').textContent=l.memory_hook||'';renderQuestions(normalizeQuestions(l.check_questions));$('#quizResult').classList.add('hidden');$('#sourceList').innerHTML=(result.sources||[]).map(s=>`<div class="source-item"><strong>${escapeHtml(s.title)} — ${escapeHtml(s.section)}</strong><span>${escapeHtml(s.publisher)}</span><p>${escapeHtml(s.text)}</p></div>`).join('');$('#lessonState').classList.remove('hidden');$('#resultPanel').scrollIntoView({behavior:'smooth'});loadHistory()}
$('#lessonForm').addEventListener('submit',async e=>{e.preventDefault();if(state.busy)return;const subject=$('#subject').value,concept=$('#concept').value.trim().replace(/\s+/g,' '),question=$('#lessonQuestion').value.trim().replace(/\s+/g,' '),formError=$('#lessonFormError');if(!subject||!question){formError.textContent=!subject?'Select a subject that has uploaded learning material.':'Enter the specific question you want answered.';formError.classList.remove('hidden');return}formError.classList.add('hidden');const request={concept,question,subject,language:$('#language').value,minutes:Number($('#minutes').value),level:Number($('#level').value),refresh:$('#refresh').checked};setBusy(true);$('#resultPanel').scrollIntoView({behavior:'smooth'});try{renderLesson(await api('/api/lesson',{method:'POST',body:JSON.stringify(request)}),request);loadMemories()}catch(err){showError(err)}});
$('#memoryForm').addEventListener('submit',async e=>{e.preventDefault();const content=$('#memoryText').value.trim();if(!content)return;try{await api('/api/memory',{method:'POST',body:JSON.stringify({content,kind:$('#memoryKind').value,subject:$('#subject').value,concept:$('#concept').value.trim()})});$('#memoryText').value='';$('#memoryToast').textContent='Saved locally. It will be used only when relevant.';loadMemories()}catch(err){$('#memoryToast').textContent=err.message||'Could not save.'}});
$('#quizForm').addEventListener('submit',async e=>{e.preventDefault();const cards=$$('.question-card'),answers=[];for(let i=0;i<cards.length;i++){const chosen=$(`input[name="q${i}"]:checked`);if(!chosen){$('#quizResult').textContent='Please answer all three questions.';$('#quizResult').classList.remove('hidden');return}answers.push(Number(chosen.value))}const difficulty=$('input[name="difficulty"]:checked').value;try{const r=await api(`/api/lessons/${state.currentLessonId}/check`,{method:'POST',body:JSON.stringify({answers,difficulty})});cards.forEach((card,i)=>{card.classList.add('reviewed');card.querySelectorAll('.option').forEach((o,j)=>o.classList.add(j===r.review[i].correct_index?'correct':j===answers[i]?'wrong':''))});$('#quizResult').innerHTML=`You recalled <strong>${r.score} of ${r.total}</strong>. Current mastery for this concept: <strong>${Math.round(r.mastery.mastery*100)}%</strong>.`;$('#quizResult').classList.remove('hidden')}catch(err){$('#quizResult').textContent=err.message||'Could not save your answers.';$('#quizResult').classList.remove('hidden')}});
$('#printButton').addEventListener('click',()=>print());
async function loadProgress(){try{const p=await api('/api/progress');$('#metricGrid').innerHTML=[['Verified lessons',p.verified_lessons],['Concepts studied',p.concepts_studied],['Recall checks',p.check_attempts],['Check accuracy',`${Math.round(p.check_accuracy*100)}%`]].map(x=>`<div class="metric card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#masteryList').innerHTML=p.mastery.length?p.mastery.map(m=>`<div class="mastery-row"><div><strong>${escapeHtml(m.concept)}</strong><small>${escapeHtml(m.subject)} • ${m.attempts} attempt${m.attempts===1?'':'s'}</small></div><div class="mastery-bar"><i style="width:${Math.round(m.score*100)}%"></i></div><b>${Math.round(m.score*100)}%</b></div>`).join(''):'<div class="empty-mini">Complete a recall check to begin measuring mastery.</div>';state.history=await api('/api/history');$('#fullHistory').innerHTML=historyMarkup(state.history,true);bindHistory($('#fullHistory'))}catch{}}
async function loadLibrary(){const marker=$('#libraryState');marker.textContent='Loading knowledge hierarchy…';marker.className='library-state';try{[state.documents,state.hierarchy]=await Promise.all([api('/api/documents'),api('/api/library/hierarchy')]);renderLibraryFilters();renderLibrary();renderDocuments()}catch(error){marker.textContent=error.message||'Knowledge library unavailable. Retry when the local service is ready.';marker.className='library-state failed';$('#contentInventory').innerHTML='';$('#documentList').innerHTML='<div class="empty-mini">Uploaded document history is unavailable.</div>'}}
function renderLibraryFilters(){const subjects=[...new Set(state.hierarchy.documents.map(x=>x.subject).filter(Boolean))];const subject=$('#librarySubjectFilter').value,book=$('#libraryBookFilter').value;$('#librarySubjectFilter').innerHTML='<option value="">All subjects</option>'+subjects.map(x=>`<option>${escapeHtml(x)}</option>`).join('');$('#librarySubjectFilter').value=subjects.includes(subject)?subject:'';const docs=state.hierarchy.documents.filter(x=>!$('#librarySubjectFilter').value||x.subject===$('#librarySubjectFilter').value);$('#libraryBookFilter').innerHTML='<option value="">All books</option>'+docs.map(x=>`<option value="${x.id}">${escapeHtml(x.title)}</option>`).join('');$('#libraryBookFilter').value=docs.some(x=>String(x.id)===book)?book:''}
function nodeRow(node,depth,hasChildren){const open=state.expandedNodes.has(node.id),status=(node.approval_status||'PENDING').toLowerCase();return `<div class="hierarchy-node" data-depth="${depth}"><button class="node-toggle" data-node-toggle="${escapeHtml(node.id)}" ${hasChildren?'':'disabled'} aria-expanded="${open}">${hasChildren?(open?'−':'+'):'•'}</button><div class="node-copy"><strong>${escapeHtml(node.display_name)}</strong><small>${escapeHtml(node.node_type)} · pages ${node.page_start||'—'}${node.page_end&&node.page_end!==node.page_start?`–${node.page_end}`:''} · ${escapeHtml(node.name_origin||'extracted')}</small></div><span class="node-count">${node.concept_count||node.child_count||0}</span><span class="approval ${status}">${escapeHtml(node.approval_status||'PENDING')}</span>${['topic','subtopic'].includes(node.node_type)?`<button class="review-topic" data-review-topic="${escapeHtml(node.id)}">Review</button>`:''}</div>`}
function renderLibrary(){const q=$('#librarySearch').value.trim(),subject=$('#librarySubjectFilter').value,doc=$('#libraryBookFilter').value,nodes=state.hierarchy.nodes.filter(n=>(!subject||n.subject===subject)&&(!doc||String(n.document_id)===doc)&&(!q||normalizeName(`${n.subject} ${n.book} ${n.display_name}`).includes(normalizeName(q))));const marker=$('#libraryState');$('#libraryCount').textContent=`${nodes.length} item${nodes.length===1?'':'s'}`;if(!nodes.length){marker.textContent=q?'No results. Try a broader name or clear a filter.':'No processed topics yet. Upload a book or add a manual topic.';marker.className='library-state empty';$('#contentInventory').innerHTML='';return}marker.textContent='';marker.className='library-state hidden';if(q){$('#contentInventory').innerHTML=nodes.map(n=>`<div class="search-result"><strong>${escapeHtml(n.display_name)}</strong><small>${escapeHtml([n.subject,n.book,n.node_type].filter(Boolean).join(' › '))} · pages ${n.page_start||'—'}</small>${['topic','subtopic'].includes(n.node_type)?`<button class="review-topic" data-review-topic="${escapeHtml(n.id)}">Review</button>`:''}</div>`).join('');return}const byParent=new Map();nodes.forEach(n=>{const list=byParent.get(n.parent_id)||[];list.push(n);byParent.set(n.parent_id,list)});const walk=(parent,depth)=>{const children=byParent.get(parent)||[];return children.map(n=>nodeRow(n,depth,(byParent.get(n.id)||[]).length>0)+(state.expandedNodes.has(n.id)?walk(n.id,depth+1):'')).join('')};const docs=state.hierarchy.documents.filter(d=>(!subject||d.subject===subject)&&(!doc||String(d.id)===doc));$('#contentInventory').innerHTML=docs.map(d=>{const id=`book-${d.id}`,open=state.expandedNodes.has(id),roots=nodes.filter(n=>n.document_id===d.id&&(!n.parent_id||!nodes.some(x=>x.id===n.parent_id)));return `<section class="tree-book"><div class="hierarchy-node subject-book"><button class="node-toggle" data-node-toggle="${id}" aria-expanded="${open}">${open?'−':'+'}</button><div class="node-copy"><strong>${escapeHtml(d.subject)} › ${escapeHtml(d.title)}</strong><small>${escapeHtml(d.status)} · ${d.records} approved concepts</small></div><span class="node-count">${roots.length}</span></div>${open?roots.map(n=>nodeRow(n,1,(byParent.get(n.id)||[]).length>0)+(state.expandedNodes.has(n.id)?walk(n.id,2):'')).join(''):''}</section>`}).join('')}
$('#librarySearch').addEventListener('input',renderLibrary);$('#librarySubjectFilter').addEventListener('change',()=>{renderLibraryFilters();renderLibrary()});$('#libraryBookFilter').addEventListener('change',renderLibrary);$('#refreshHierarchy').addEventListener('click',loadLibrary);
$('#contentInventory').addEventListener('click',async e=>{const toggle=e.target.closest('[data-node-toggle]'),review=e.target.closest('[data-review-topic]');if(toggle){const id=toggle.dataset.nodeToggle;state.expandedNodes.has(id)?state.expandedNodes.delete(id):state.expandedNodes.add(id);renderLibrary();return}if(review){const node=state.hierarchy.nodes.find(x=>x.id===review.dataset.reviewTopic);const name=prompt('Rename this topic or sub-topic. Leave unchanged to review status only.',node.display_name);if(name===null)return;const action=normalizeName(name)!==normalizeName(node.display_name)?'rename':(confirm('Approve this identified name? Choose Cancel to reject it.')?'approve':'reject');try{await api(`/api/topics/${node.id}`,{method:'PATCH',body:JSON.stringify({action,display_name:name})});await Promise.all([loadCatalog(),loadLibrary()])}catch(error){alert(error.message||'The correction could not be saved.')}}});
function renderDocuments(){const book=($('#documentBookFilter')?.value||'').trim().toLowerCase(),author=($('#documentAuthorFilter')?.value||'').trim().toLowerCase(),items=state.documents.filter(item=>(!book||`${item.title} ${item.file_name}`.toLowerCase().includes(book))&&(!author||(item.publisher||'').toLowerCase().includes(author)));$('#documentList').innerHTML=items.length?items.map(item=>`<article class="document-row"><div class="file-type">${escapeHtml(item.file_type.toUpperCase())}</div><div class="document-main"><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.publisher||'Author not specified')}${item.edition?` · ${escapeHtml(item.edition)}`:''} · ${escapeHtml(item.subject)} · ${item.records||0} records</small>${item.error_message?`<p>${escapeHtml(safeUiText(item.error_message,'This document could not be processed. Retry it or review the Dell service log.'))}</p>`:''}</div><div class="document-actions"><span class="document-status ${item.status.toLowerCase()}">${escapeHtml(item.status.replace('_',' '))}</span>${!String(item.id).startsWith('disk:')?`<button class="text-button" type="button" data-reprocess-book="${item.id}">Reprocess topics</button><button class="danger-button" type="button" data-delete-book="${item.id}">Delete book</button>`:''}</div></article>`).join(''):'<div class="empty-mini">No books match these filters.</div>'}
$('#documentBookFilter').addEventListener('input',renderDocuments);$('#documentAuthorFilter').addEventListener('input',renderDocuments);
$('#documentList').addEventListener('input',e=>{if(!e.target.matches('.topic-book-filter'))return;const q=e.target.value.trim().toLowerCase(),details=e.target.closest('.book-topics');details.querySelectorAll('.book-topic').forEach(row=>row.classList.toggle('hidden',!row.dataset.topicText.includes(q)))});
$('#documentList').addEventListener('click',async e=>{const bookButton=e.target.closest('[data-delete-book]'),reprocess=e.target.closest('[data-reprocess-book]');if(!bookButton&&!reprocess)return;if(reprocess){if(!confirm('Reprocess this book locally? Existing approvals and administrator corrections will be preserved.'))return;reprocess.disabled=true;showUploadStatus('working','Reprocessing headings and page ranges. This may take several minutes.');try{const result=await api(`/api/documents/${reprocess.dataset.reprocessBook}/reprocess`,{method:'POST',body:'{}'});showUploadStatus('success',`Reprocessing complete: ${result.records} chunks retained.`);await Promise.all([loadCatalog(),loadLibrary()])}catch(error){showUploadStatus('error',error.message||'Reprocessing failed; the existing library remains recoverable.')}finally{reprocess.disabled=false}return}const item=state.documents.find(x=>String(x.id)===bookButton.dataset.deleteBook);if(!confirm(`Delete “${item?.title||'this book'}” and every topic imported from it? Topics from other books will remain.`))return;try{const result=await api(`/api/documents/${bookButton.dataset.deleteBook}`,{method:'DELETE'});showUploadStatus('success',result.message);await Promise.all([loadCatalog(),loadLibrary()])}catch(error){showUploadStatus('error',error.message||'The book could not be deleted.')}});
function showUploadStatus(kind,message){const box=$('#uploadStatus');box.className=`upload-status ${kind}`;box.textContent=message;box.classList.remove('hidden')}
$('#uploadFile').addEventListener('change',()=>{const file=$('#uploadFile').files[0];$('#fileDropTitle').textContent=file?file.name:'Choose a document';$('#fileDropDetail').textContent=file?`${(file.size/1024/1024).toFixed(1)} MB · ready to upload`:'or drag it here · maximum 150 MB';if(file&&!$('#uploadTitle').value)$('#uploadTitle').value=file.name.replace(/\.[^.]+$/,'')});
$('#uploadForm').addEventListener('submit',async e=>{e.preventDefault();const file=$('#uploadFile').files[0],subject=$('#uploadSubject').value.trim();if(!file){showUploadStatus('error','Choose a document first.');return}if(!subject){showUploadStatus('error','Enter the subject for this document.');return}if(!$('#uploadAuthorized').checked){showUploadStatus('error','Confirm that you are authorized to use this document.');return}const button=$('#uploadButton');button.disabled=true;button.textContent='Uploading and converting...';showUploadStatus('working','Checking the local server, then uploading securely to this Dell. Large PDFs may take several minutes.');try{const config=await api('/api/config');if(!config.features?.includes('document_upload'))throw{status:'UPLOAD_UNAVAILABLE',message:'Document upload is unavailable at this portal address. Open the current Worker portal and retry.'};const headers={'X-File-Name':file.name,'X-Subject':subject,'X-Title':$('#uploadTitle').value.trim(),'X-Default-Topic':$('#uploadTopic').value.trim(),'X-Publisher':$('#uploadPublisher').value.trim(),'X-Edition':$('#uploadEdition').value.trim(),'X-License-Note':'User confirms authorization for private educational use.'};showUploadStatus('working','Uploading and converting the document. Please keep this page open.');const result=await api('/api/upload',{method:'POST',headers,body:file});showUploadStatus('success',`${result.message} You can choose another book now.`);$('#uploadForm').reset();$('#fileDropTitle').textContent='Choose another document';$('#fileDropDetail').textContent='or drag it here · maximum 150 MB';await Promise.all([loadCatalog(),loadLibrary()]);$('#uploadFile').focus()}catch(error){showUploadStatus('error',error.message||'The document could not be processed.')}finally{button.disabled=false;button.textContent='Convert and add to library'}});
$('#refreshLibrary').addEventListener('click',()=>Promise.all([loadCatalog(),loadLibrary()]));
function memoryMarkup(items,compact=false){if(!items.length)return '<div class="empty-mini">No preferences saved yet. The model can suggest one after a lesson.</div>';return items.map(m=>`<div class="memory-row${compact?' compact':''}"><b>${escapeHtml(m.kind==='model_preference'?'Model default':m.kind)}</b><span>${escapeHtml(m.content)}</span><small>${escapeHtml(m.subject||'All subjects')}</small><button class="delete-memory" type="button" data-delete-memory="${m.id}" aria-label="Delete preference">Delete</button></div>`).join('')}
async function loadMemories(){try{const items=await api('/api/memories'),preferences=items.filter(m=>['preference','model_preference'].includes(m.kind));$('#memoryInventory').innerHTML=memoryMarkup(items);$('#quickPreferences').innerHTML=memoryMarkup(preferences.slice(0,4),true)}catch{}}
async function deleteMemory(event){const button=event.target.closest('[data-delete-memory]');if(!button)return;if(!confirm('Delete this saved preference?'))return;try{await api(`/api/memories/${button.dataset.deleteMemory}`,{method:'DELETE'});$('#memoryToast').textContent='Preference deleted.';loadMemories()}catch(error){$('#memoryToast').textContent=error.message||'Preference could not be deleted.'}}
$('#memoryInventory').addEventListener('click',deleteMemory);$('#quickPreferences').addEventListener('click',deleteMemory);
async function loadSettings(){renderConfig();checkHealth()}
Promise.all([loadConfig(),loadHistory(),loadCatalog(),loadMemories(),checkHealth()]);
